name: Terraform Apply and S3 Sync

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
      
      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Set bucket name from Terraform output
        id: get_bucket
        run: echo "BUCKET_NAME=$(terraform output -raw bucket_name)" >> $GITHUB_ENV

      - name: Debug bucket name
        run: |
           echo "Using bucket: $BUCKET_NAME"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Change as needed

      - name: Sync static site to S3
        # run: aws s3 sync ./oxer-html s3://$BUCKET_NAME --delete
        run: aws s3 sync ./oxer-html s3://$BUCKET_NAME --delete --exact-timestamps
        # if: env.BUCKET_NAME != ''
        # run: aws s3 sync ./oxer-html s3://$BUCKET_NAME --delete


    #   - name: Set bucket name from Terraform output
    #     run: echo "BUCKET_NAME=$(terraform output -raw bucket_name)" >> $GITHUB_ENV

    #   - name: Sync static site to S3
    #     run: aws s3 sync ./oxer-html s3://$BUCKET_NAME --delete

     
    #   - name: Get Bucket Name
    #     id: get-bucket
    #     run: |
    #       echo "BUCKET_NAME=$(terraform output -raw bucket_name)" >> $GITHUB_ENV
    
    #   - name: Sync static site to S3
    #     run: aws s3 sync ./oxer-html s3://my-tf-bucket-${{ steps.terraform.outputs.bucket_suffix }}/ --delete

    #   - name: Sync Static Website to S3
    #     run: |
    #       aws s3 sync ./oxer-html s3://${{ env.BUCKET_NAME }}/ --delete